spring:
  datasource:
    url: jdbc:postgresql://3.235.170.15:5432/gis
    username: guest
    password: U8OPtddp
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect
        # dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl